# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('chat_id', models.CharField(max_length=64)),
                ('chat_type', models.IntegerField(choices=[(0, 'Privado'), (1, 'Grupo'), (2, 'Supergrupo'), (3, 'Canal')], default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='remotechat',
            unique_together=set([('chat_id', 'chat_type')]),
        ),
    ]
