# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotechat',
            name='items_per_page',
            field=models.IntegerField(default=10),
        ),
    ]
