language: python

python:
  - "2.7"
  - "3.6"

branches:
  only:
    - master

before_install:
  - pip install pip --upgrade
  - pip install -r requirements.txt

install:
  - python manage.py test

before_script:
  - pip install coverage==4.4.2

script:
  - coverage run --source='.' manage.py test
  - coverage report -m --skip-covered
