# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('sensor_type', models.IntegerField(choices=[(0, 'Integer'), (1, 'Float'), (2, 'String')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Seta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('sensors', models.ManyToManyField(to='base.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='ValueSensorSeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512)),
                ('date', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Sensor')),
                ('seta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Seta')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
