# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.FileField(upload_to=b'')),
                ('date', models.DateTimeField(auto_now=True)),
                ('processed', models.BooleanField(default=False)),
                ('seta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Seta')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
