# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bulkdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='seta',
            name='check_bulk',
            field=models.BooleanField(default=False, help_text='Check the columns when bulk file is uploaded (you could lost information)'),
        ),
        migrations.AddField(
            model_name='seta',
            name='check_value',
            field=models.BooleanField(default=False, help_text='Check the value stored for the sensors (you could lost information)'),
        ),
        migrations.AddField(
            model_name='seta',
            name='date_column',
            field=models.CharField(default='date', help_text='Date name column used into the bulk file, for CSV', max_length=32),
        ),
        migrations.AddField(
            model_name='seta',
            name='date_parse',
            field=models.CharField(blank=True, default='', help_text='Date format used into the bulk file, for CSV (required for parse the file)', max_length=16),
        ),
        migrations.AddField(
            model_name='seta',
            name='decimal',
            field=models.CharField(default=',', help_text='Decimal separator used into the bulk file, for CSV', max_length=1),
        ),
        migrations.AddField(
            model_name='seta',
            name='separator',
            field=models.CharField(default=';', help_text='Separator used into the bulk file, for CSV', max_length=1),
        ),
    ]
